# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: instruments.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'instruments_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module InstrumentsService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.InstrumentsService'

                # TradingSchedules — расписания торговых площадок
                rpc :TradingSchedules, ::Tinkoff::Public::Invest::Api::Contract::V1::TradingSchedulesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::TradingSchedulesResponse
                # BondBy — получить облигацию по ее идентификатору
                rpc :BondBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::BondResponse
                # Bonds — список облигаций
                rpc :Bonds, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::BondsResponse
                # GetBondCoupons — график выплат купонов по облигации
                rpc :GetBondCoupons, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondCouponsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondCouponsResponse
                # GetBondEvents — события по облигации
                rpc :GetBondEvents, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondEventsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondEventsResponse
                # CurrencyBy — получить валюту по ее идентификатору
                rpc :CurrencyBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CurrencyResponse
                # Currencies — список валют
                rpc :Currencies, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CurrenciesResponse
                # EtfBy — получить инвестиционный фонд по его идентификатору
                rpc :EtfBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::EtfResponse
                # Etfs — список инвестиционных фондов
                rpc :Etfs, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::EtfsResponse
                # FutureBy — получить фьючерс по его идентификатору
                rpc :FutureBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::FutureResponse
                # Futures — список фьючерсов
                rpc :Futures, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::FuturesResponse
                # OptionBy — получить опцион по его идентификатору
                rpc :OptionBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OptionResponse
                # Deprecated Options — список опционов
                rpc :Options, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OptionsResponse
                # OptionsBy — список опционов
                rpc :OptionsBy, ::Tinkoff::Public::Invest::Api::Contract::V1::FilterOptionsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OptionsResponse
                # ShareBy — получить акцию по ее идентификатору
                rpc :ShareBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::ShareResponse
                # Shares — список акций
                rpc :Shares, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::SharesResponse
                # Indicatives — индикативные инструменты — индексы, товары и другие
                rpc :Indicatives, ::Tinkoff::Public::Invest::Api::Contract::V1::IndicativesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::IndicativesResponse
                # GetAccruedInterests — накопленный купонный доход по облигации
                rpc :GetAccruedInterests, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccruedInterestsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccruedInterestsResponse
                # GetFuturesMargin — размера гарантийного обеспечения по фьючерсам
                rpc :GetFuturesMargin, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFuturesMarginRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFuturesMarginResponse
                # GetInstrumentBy — основная информация об инструменте
                rpc :GetInstrumentBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentResponse
                # GetDividends — события выплаты дивидендов по инструменту
                rpc :GetDividends, ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsResponse
                # GetAssetBy — получить актив по его идентификатору
                rpc :GetAssetBy, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetResponse
                # GetAssets — список активов
                # Метод работает для всех инструментов, кроме срочных — фьючерсов и опционов
                rpc :GetAssets, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetsResponse
                # GetFavorites — получить список избранных инструментов
                rpc :GetFavorites, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoritesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoritesResponse
                # EditFavorites — отредактировать список избранных инструментов
                rpc :EditFavorites, ::Tinkoff::Public::Invest::Api::Contract::V1::EditFavoritesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::EditFavoritesResponse
                # CreateFavoriteGroup — создать новую группу избранных инструментов
                rpc :CreateFavoriteGroup, ::Tinkoff::Public::Invest::Api::Contract::V1::CreateFavoriteGroupRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CreateFavoriteGroupResponse
                # DeleteFavoriteGroup — удалить группу избранных инструментов
                rpc :DeleteFavoriteGroup, ::Tinkoff::Public::Invest::Api::Contract::V1::DeleteFavoriteGroupRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::DeleteFavoriteGroupResponse
                # GetFavoriteGroups — список групп избранных инструментов
                rpc :GetFavoriteGroups, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoriteGroupsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoriteGroupsResponse
                # GetCountries — список стран
                rpc :GetCountries, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCountriesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCountriesResponse
                # FindInstrument — найти инструмент
                rpc :FindInstrument, ::Tinkoff::Public::Invest::Api::Contract::V1::FindInstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::FindInstrumentResponse
                # GetBrands — список брендов
                rpc :GetBrands, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandsResponse
                # GetBrandBy — получить бренд по его идентификатору
                rpc :GetBrandBy, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::Brand
                # GetAssetFundamentals — фундаментальные показатели по активу
                rpc :GetAssetFundamentals, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAssetFundamentalsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAssetFundamentalsResponse
                # GetAssetReports — расписания выхода отчетностей эмитентов
                rpc :GetAssetReports, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAssetReportsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAssetReportsResponse
                # GetConsensusForecasts — мнения аналитиков по инструменту
                rpc :GetConsensusForecasts, ::Tinkoff::Public::Invest::Api::Contract::V1::GetConsensusForecastsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetConsensusForecastsResponse
                # GetForecastBy — прогнозы инвестдомов по инструменту
                rpc :GetForecastBy, ::Tinkoff::Public::Invest::Api::Contract::V1::GetForecastRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetForecastResponse
                # GetRiskRates — ставки риска по инструменту
                rpc :GetRiskRates, ::Tinkoff::Public::Invest::Api::Contract::V1::RiskRatesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::RiskRatesResponse
                # GetInsiderDeals —  сделки инсайдеров по инструментам
                rpc :GetInsiderDeals, ::Tinkoff::Public::Invest::Api::Contract::V1::GetInsiderDealsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetInsiderDealsResponse
                # StructuredNoteBy — получить структурную ноту по ее идентификатору
                rpc :StructuredNoteBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::StructuredNoteResponse
                # StructuredNotes — список структурных нот
                rpc :StructuredNotes, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::StructuredNotesResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Методы сервиса предназначены для получения:<br/>1. Информации об инструментах.<br/>2.
            # Расписания торговых сессий.<br/>3. Календаря выплат купонов по облигациям.<br/>4.
            # Размера гарантийного обеспечения по фьючерсам.<br/>5. Дивидендов по ценной бумаге.
          end
        end
      end
    end
  end
end
