# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: marketdata.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'marketdata_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module MarketDataService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.MarketDataService'

                # GetCandles — исторические свечи по инструменту
                rpc :GetCandles, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCandlesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCandlesResponse
                # GetLastPrices — цены последних сделок по инструментам
                rpc :GetLastPrices, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastPricesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastPricesResponse
                # GetOrderBook — стакан по инструменту
                rpc :GetOrderBook, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderBookRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderBookResponse
                # GetTradingStatus — статус торгов по инструменту
                rpc :GetTradingStatus, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusResponse
                # GetTradingStatuses — статус торгов по инструментам
                rpc :GetTradingStatuses, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusesResponse
                # GetLastTrades — обезличенные сделки
                # Обезличенные сделки по инструменту. Метод гарантирует получение информации за последний час.
                rpc :GetLastTrades, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastTradesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastTradesResponse
                # GetClosePrices — цены закрытия торговой сессии по инструментам
                rpc :GetClosePrices, ::Tinkoff::Public::Invest::Api::Contract::V1::GetClosePricesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetClosePricesResponse
                # GetTechAnalysis — технические индикаторы по инструменту
                rpc :GetTechAnalysis, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTechAnalysisRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTechAnalysisResponse
                # GetMarketValues — рыночные данные по инструментам
                rpc :GetMarketValues, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarketValuesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarketValuesResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис для получения биржевой информации:<br/> 1. Свечи.<br/> 2. Стаканы.<br/> 3. Торговые статусы.<br/> 4. Лента сделок.
            module MarketDataStreamService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.MarketDataStreamService'

                # MarketDataStream — bidirectional стрим предоставления биржевой информации
                rpc :MarketDataStream, stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataRequest), stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataResponse)
                # MarketDataServerSideStream — server-side стрим предоставления биржевой информации
                rpc :MarketDataServerSideStream, ::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataServerSideStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataResponse)
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
