# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: operations.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'operations_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module OperationsService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OperationsService'

                # GetOperations — список операций по счету
                # При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
                rpc :GetOperations, ::Tinkoff::Public::Invest::Api::Contract::V1::OperationsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OperationsResponse
                # GetPortfolio — портфель по счету
                rpc :GetPortfolio, ::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioResponse
                # GetPositions — список позиций по счету
                rpc :GetPositions, ::Tinkoff::Public::Invest::Api::Contract::V1::PositionsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PositionsResponse
                # GetWithdrawLimits — доступный остаток для вывода средств
                rpc :GetWithdrawLimits, ::Tinkoff::Public::Invest::Api::Contract::V1::WithdrawLimitsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::WithdrawLimitsResponse
                # GetBrokerReport — брокерский отчет.
                rpc :GetBrokerReport, ::Tinkoff::Public::Invest::Api::Contract::V1::BrokerReportRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::BrokerReportResponse
                # GetDividendsForeignIssuer — отчет «Справка о доходах за пределами РФ»
                rpc :GetDividendsForeignIssuer, ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsForeignIssuerRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsForeignIssuerResponse
                # GetOperationsByCursor — список операций по счету с пагинацией
                # При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
                rpc :GetOperationsByCursor, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOperationsByCursorRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOperationsByCursorResponse
              end

              Stub = Service.rpc_stub_class
            end
            # С помощью методов сервиса можно получить:<br/><br/> **1**. Список операций по счету.<br/> **2**.
            # Портфель по счету.<br/> **3**. Позиции ценных бумаг на счете.<br/> **4**.
            # Доступный остаток для вывода средств.<br/> **5**. Различные отчеты.
            module OperationsStreamService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OperationsStreamService'

                # PortfolioStream — стрим обновлений портфеля
                rpc :PortfolioStream, ::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioStreamResponse)
                # PositionsStream — стрим обновлений информации по изменению позиций портфеля
                rpc :PositionsStream, ::Tinkoff::Public::Invest::Api::Contract::V1::PositionsStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::PositionsStreamResponse)
                # OperationsStream — стрим обновлений операций
                rpc :OperationsStream, ::Tinkoff::Public::Invest::Api::Contract::V1::OperationsStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::OperationsStreamResponse)
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
