# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: orders.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'orders_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module OrdersStreamService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OrdersStreamService'

                # TradesStream — стрим сделок пользователя
                rpc :TradesStream, ::Tinkoff::Public::Invest::Api::Contract::V1::TradesStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::TradesStreamResponse)
                # OrderStateStream — стрим поручений пользователя
                # Перед работой прочитайте [статью](/invest/services/orders/orders_state_stream).
                rpc :OrderStateStream, ::Tinkoff::Public::Invest::Api::Contract::V1::OrderStateStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::OrderStateStreamResponse)
              end

              Stub = Service.rpc_stub_class
            end

            module OrdersService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OrdersService'

                # PostOrder — выставить заявку
                rpc :PostOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
                # PostOrderAsync — выставить заявку асинхронным методом
                # Особенности работы приведены в [статье](/invest/services/orders/async).
                rpc :PostOrderAsync, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderAsyncRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderAsyncResponse
                # CancelOrder — отменить заявку
                rpc :CancelOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderResponse
                # GetOrderState — получить статус торгового поручения
                rpc :GetOrderState, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderStateRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OrderState
                # GetOrders — получить список активных заявок по счету
                rpc :GetOrders, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersResponse
                # ReplaceOrder — изменить выставленную заявку
                rpc :ReplaceOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::ReplaceOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
                # GetMaxLots — расчет количества доступных для покупки/продажи лотов
                rpc :GetMaxLots, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMaxLotsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMaxLotsResponse
                # GetOrderPrice — получить предварительную стоимость для лимитной заявки
                rpc :GetOrderPrice, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderPriceRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderPriceResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис предназначен для работы с торговыми поручениями:<br/> **1**.
            # выставление;<br/> **2**. отмена;<br/> **3**. получение статуса;<br/> **4**.
            # расчет полной стоимости;<br/> **5**. получение списка заявок.
          end
        end
      end
    end
  end
end
