# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sandbox.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'sandbox_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module SandboxService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.SandboxService'

                # OpenSandboxAccount — зарегистрировать счет
                rpc :OpenSandboxAccount, ::Tinkoff::Public::Invest::Api::Contract::V1::OpenSandboxAccountRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OpenSandboxAccountResponse
                # GetSandboxAccounts — счета пользователя
                rpc :GetSandboxAccounts, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsResponse
                # CloseSandboxAccount — закрыть счет
                rpc :CloseSandboxAccount, ::Tinkoff::Public::Invest::Api::Contract::V1::CloseSandboxAccountRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CloseSandboxAccountResponse
                # PostSandboxOrder — выставить заявку
                rpc :PostSandboxOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
                # PostSandboxOrderAsync — выставить заявку асинхронным методом
                # Особенности работы приведены в [статье](/invest/services/orders/async).
                rpc :PostSandboxOrderAsync, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderAsyncRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderAsyncResponse
                # ReplaceSandboxOrder — изменить выставленную заявку
                rpc :ReplaceSandboxOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::ReplaceOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
                # GetSandboxOrders — получить список активных заявок по счету
                rpc :GetSandboxOrders, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersResponse
                # CancelSandboxOrder — отменить заявку
                rpc :CancelSandboxOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderResponse
                # GetSandboxOrderState — получить статус торгового поручения
                rpc :GetSandboxOrderState, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderStateRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OrderState
                # GetSandboxOrderPrice — получить предварительную стоимость для лимитной заявки
                rpc :GetSandboxOrderPrice, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderPriceRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderPriceResponse
                # GetSandboxPositions — список позиций по счету
                rpc :GetSandboxPositions, ::Tinkoff::Public::Invest::Api::Contract::V1::PositionsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PositionsResponse
                # GetSandboxOperations — список операций по счету
                # При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
                rpc :GetSandboxOperations, ::Tinkoff::Public::Invest::Api::Contract::V1::OperationsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::OperationsResponse
                # GetSandboxOperationsByCursor — список операций по счету с пагинацией
                # При работе с методом учитывайте [особенности взаимодействия](/invest/services/operations/operations_problems).
                rpc :GetSandboxOperationsByCursor, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOperationsByCursorRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOperationsByCursorResponse
                # GetSandboxPortfolio — портфель по счету
                rpc :GetSandboxPortfolio, ::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PortfolioResponse
                # SandboxPayIn — пополнить счет.
                rpc :SandboxPayIn, ::Tinkoff::Public::Invest::Api::Contract::V1::SandboxPayInRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::SandboxPayInResponse
                # GetSandboxWithdrawLimits — доступный остаток для вывода средств
                rpc :GetSandboxWithdrawLimits, ::Tinkoff::Public::Invest::Api::Contract::V1::WithdrawLimitsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::WithdrawLimitsResponse
                # GetSandboxMaxLots — расчет количества доступных для покупки/продажи лотов
                rpc :GetSandboxMaxLots, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMaxLotsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMaxLotsResponse
                # PostSandboxStopOrder — выставить стоп-заявку
                rpc :PostSandboxStopOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::PostStopOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostStopOrderResponse
                # GetSandboxStopOrders — получить список активных стоп-заявок по счету
                rpc :GetSandboxStopOrders, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStopOrdersRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStopOrdersResponse
                # CancelSandboxStopOrder — отменить стоп-заявку
                rpc :CancelSandboxStopOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelStopOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelStopOrderResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Методы для работы с песочницей T-Invest API
          end
        end
      end
    end
  end
end
