# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: signals.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'signals_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module SignalService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.SignalService'

                # GetStrategies — стратегии
                rpc :GetStrategies, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStrategiesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStrategiesResponse
                # GetSignals — сигналы
                rpc :GetSignals, ::Tinkoff::Public::Invest::Api::Contract::V1::GetSignalsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetSignalsResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис для получения технических сигналов и мнений аналитиков по инструментам.
          end
        end
      end
    end
  end
end
