# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: users.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'users_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module UsersService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.UsersService'

                # GetAccounts — счета пользователя
                # Получить список счетов.
                rpc :GetAccounts, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsResponse
                # GetMarginAttributes — маржинальные показатели по счeту
                # Метод позволяет получить маржинальные показатели и ликвидность по заданному счeту.
                rpc :GetMarginAttributes, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarginAttributesRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarginAttributesResponse
                # GetUserTariff — тариф пользователя
                # Получить информацию о текущих лимитах на подклчение, согласно текущему тарифу пользователя.
                rpc :GetUserTariff, ::Tinkoff::Public::Invest::Api::Contract::V1::GetUserTariffRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetUserTariffResponse
                # GetInfo — информация о пользователе
                # Получить информацию о пользователе: тариф, признак квалификации, пройденные тесты и др.
                rpc :GetInfo, ::Tinkoff::Public::Invest::Api::Contract::V1::GetInfoRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetInfoResponse
                # GetBankAccounts — банковские счета пользователя
                # Получить список счетов пользователя, в том числе и банковских.
                rpc :GetBankAccounts, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBankAccountsRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBankAccountsResponse
                # CurrencyTransfer — перевод денежных средств между счетами
                # Перевести денежные средства между брокерскими счетами
                rpc :CurrencyTransfer, ::Tinkoff::Public::Invest::Api::Contract::V1::CurrencyTransferRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CurrencyTransferResponse
                # PayIn — пополнение брокерского счета
                # Пополнить брокерский счёт с банковского
                rpc :PayIn, ::Tinkoff::Public::Invest::Api::Contract::V1::PayInRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PayInResponse
              end

              Stub = Service.rpc_stub_class
            end
            # С помощью сервиса можно получить: <br/> 1.
            # список счетов пользователя; <br/> 2. маржинальные показатели по счeту.
          end
        end
      end
    end
  end
end
