# frozen_string_literal: true

module TbankGrpc
  module Converters
    # Маппинг CandleInterval → SubscriptionInterval (имена констант) для стрима свечей.
    # CandleInterval — в GetCandles и др., SubscriptionInterval — в MarketDataStream.
    # Публичный API: константа CANDLE_TO_SUBSCRIPTION (Hash).
    module CandleToSubscriptionInterval
      CANDLE_TO_SUBSCRIPTION = {
        CANDLE_INTERVAL_1_MIN: :SUBSCRIPTION_INTERVAL_ONE_MINUTE,
        CANDLE_INTERVAL_2_MIN: :SUBSCRIPTION_INTERVAL_2_MIN,
        CANDLE_INTERVAL_3_MIN: :SUBSCRIPTION_INTERVAL_3_MIN,
        CANDLE_INTERVAL_5_MIN: :SUBSCRIPTION_INTERVAL_FIVE_MINUTES,
        CANDLE_INTERVAL_10_MIN: :SUBSCRIPTION_INTERVAL_10_MIN,
        CANDLE_INTERVAL_15_MIN: :SUBSCRIPTION_INTERVAL_FIFTEEN_MINUTES,
        CANDLE_INTERVAL_30_MIN: :SUBSCRIPTION_INTERVAL_30_MIN,
        CANDLE_INTERVAL_HOUR: :SUBSCRIPTION_INTERVAL_ONE_HOUR,
        CANDLE_INTERVAL_1_HOUR: :SUBSCRIPTION_INTERVAL_ONE_HOUR,
        CANDLE_INTERVAL_2_HOUR: :SUBSCRIPTION_INTERVAL_2_HOUR,
        CANDLE_INTERVAL_4_HOUR: :SUBSCRIPTION_INTERVAL_4_HOUR,
        CANDLE_INTERVAL_DAY: :SUBSCRIPTION_INTERVAL_ONE_DAY,
        CANDLE_INTERVAL_WEEK: :SUBSCRIPTION_INTERVAL_WEEK,
        CANDLE_INTERVAL_MONTH: :SUBSCRIPTION_INTERVAL_MONTH
      }.freeze
    end
  end
end
